repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
          ]
        args:
          - "--max-line-length=99"
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]
